#ifndef __VERSION_H__
#define __VERSION_H__
#define VERSION_DATE "Sun, 21 Jan 2018 10:40:15 +0000"
#define VERSION_HASH "UNKNOWN"
#define VERSION_BRANCH "UNKNOWN"
#define VERSION_REPO "UNKNOWN"
#endif
