#ifndef __VERSION_H__
#define __VERSION_H__
#define VERSION_DATE "Tue, 23 Jan 2018 11:40:35 +0000"
#define VERSION_HASH "UNKNOWN"
#define VERSION_BRANCH "UNKNOWN"
#define VERSION_REPO "UNKNOWN"
#endif
