#ifndef __VERSION_H__
#define __VERSION_H__
#define VERSION_DATE "Sun, 21 Jan 2018 14:21:37 +0000"
#define VERSION_HASH "UNKNOWN"
#define VERSION_BRANCH "UNKNOWN"
#define VERSION_REPO "UNKNOWN"
#endif
